Repository MIT-Emerging-Talent/2024-group-11-cdsp, pull requests merged in 2024-02, with the labels that each got.

#11 add documentation
  README.md
  milestone/milestone_1/research_question.md
  milestone/milestone_1/system_design_thinking.md
  retrospective/retrospective_1.md
Labels: documentation

#12 add milestone2
  milestone/milestone_2/dataset_documentation.md
  retrospective/retrospective_2.md
Labels: documentation

#13 add experience and comparitive analysis
  README.md
  milestone/milestone_2/data_collection_and_cleaning_scripts/analysis.md
  milestone/milestone_2/our_experience.md
Labels: documentation

#14 resolve link problem
  README.md
Labels: documentation

#15 Update README.md
  README.md
Labels: documentation

#16 Dmytro Zero Waste Experience
  milestone/milestone_2/our_experience.md
Labels: documentation

#18 add experience
  milestone/milestone_2/our_experience.md
Labels: documentation

#19 Denys Zero Waste Experience
  milestone/milestone_2/our_experience.md
Labels: documentation

#24 Updated README
  README.md
Labels: documentation

#25 added data sets about countries food waste
  milestone/milestone_3/food_service_waste.csv
  milestone/milestone_3/retail_food_waste.csv
Labels: data

#32 add extras
  extras/FWD (1).xlsx
  extras/Figures_-_Hours_of_work_-_annual-2022v3.xlsx
  extras/Municipal_waste_generated,_2006_and_2021_(kg_per_capita).png
  extras/Municipal_waste_generated,_in_selected_years.png
  extras/Municipal_waste_treatment,_EU,_1995-2021_(kg_per_capita).png
  extras/food-waste_usa.png
  extras/food_waste_stats.xlsx
  extras/landfilled,_incinerated,_recycled_and_composted,_EU,_1995-2021.png
  extras/marnowanie-jedzenia-deklaracje-rzeczywistosc-kraje.jpg
Labels: data, task

#34 update retrospective for milestone 1
  retrospective/retrospective_1.md
Labels: documentation

#36 add the file
  extras/Data_for_Progect.xlsx
Labels: documentation

#37 Cleaned datasets and add new datasets
  milestone/milestone_3/food_service_waste.csv
  milestone/milestone_3/household_food_waste.csv
  milestone/milestone_3/household_waste.csv
  milestone/milestone_3/retail_food_waste.csv
Labels: data

#46 fix bugs
  milestone/milestone_3/analys.ipynb
  milestone/milestone_3/food_service_waste.csv
  milestone/milestone_3/household_waste.csv
  milestone/milestone_3/retail_food_waste.csv
Labels: bug

#45 Updated_group_project_questions
  README.md
Labels: documentation, question

#51 add missed retrospective 2
  retrospective/retrospective_2.md
Labels: documentation, task

#52 add missed retrospective 3, make changes in retrospectives 1 and 2
  retrospective/retrospective_1.md
  retrospective/retrospective_2.md
  retrospective/retrospective_3.md
Labels: documentation, task

#53 root_readme_changes
  README.md
  extras/image.png
  milestone/milestone5/README.md
  milestone/milestone_4/README.md
  retrospective/retrospective_4.md
  retrospective/retrospective_5.md
Labels: documentation, data, task

#49 add more analys and readme
  milestone/milestone_3/README.md
  milestone/milestone_3/analys.ipynb
  milestone/milestone_3/analys.md
  milestone/milestone_3/analys_waste/README.md
  milestone/milestone_3/analys_waste/analys_food_service_waste.ipynb
  milestone/milestone_3/analys_waste/analys_household_waste.ipynb
  milestone/milestone_3/analys_waste/analys_retail_food_waste.ipynb
  milestone/milestone_3/analys_waste/food_service_waste.csv
  milestone/milestone_3/analys_waste/household_waste.csv
  milestone/milestone_3/analys_waste/retail_food_waste.csv
  milestone/milestone_3/prediction.ipynb
  milestone/milestone_3/result_table.csv
  milestone/milestone_3/total_analys.ipynb
  milestone/milestone_3/updated_dataset.csv
Labels: documentation, data

#47 rewrite collective learning goals
  .collaboration/learning_goals.md
Labels: documentation

#54 add analysis description
  README.md
Labels: documentation

#57 Milestone 3. README file
  extras/HDI.png
  milestone/milestone_3/README.md
  milestone/milestone_3/analysis_waste/README.md
  milestone/milestone_3/analysis_waste/analysis_food_service_waste.ipynb
  milestone/milestone_3/analysis_waste/analysis_household_waste.ipynb
  milestone/milestone_3/analysis_waste/analysis_retail_food_waste.ipynb
  milestone/milestone_3/analysis_waste/food_service_waste.csv
  milestone/milestone_3/analysis_waste/household_waste.csv
  milestone/milestone_3/analysis_waste/retail_food_waste.csv
  milestone/milestone_3/total_analysis.ipynb
  milestone/milestone_5/README.md
Labels: bug, documentation

#58 Root Readme Changes
  README.md
  extras/1-1-1180x617.png
  extras/waste_production_sector.png
  milestone/milestone_1/research_question.md
  milestone/milestone_3/research_questions.md
  milestone/milestone_3/total_analysis.ipynb
  milestone/milestone_3/updated_dataset.csv
Labels: bug, documentation, question

#59 Update README.md
  README.md
Labels: bug, documentation

#60 Update README.md
  README.md
Labels: bug, documentation

#61 Update README.md
  README.md
Labels: bug, documentation

#65 add prediction analysis
  README.md
  milestone/milestone_3/analysis_waste/analysis_retail_food_waste.ipynb
  milestone/milestone_3/prediction.ipynb
  milestone/milestone_3/prediction/README.md
  milestone/milestone_3/prediction/analysis_code.md
  milestone/milestone_3/prediction/new.ipynb
  milestone/milestone_3/prediction/prediction.csv
  milestone/milestone_3/prediction/total_waste_prediction_analysis_Canada.ipynb
  milestone/milestone_3/prediction/total_waste_prediction_analysis_Denmark.ipynb
  milestone/milestone_3/prediction/total_waste_prediction_analysis_Germany.ipynb
  milestone/milestone_3/prediction/total_waste_prediction_analysis_US.ipynb
  milestone/milestone_3/prediction/total_waste_prediction_analysis_Ukraine.ipynb
  milestone/milestone_3/prediction/total_waste_prediction_waste_analysis_Poland.ipynb
Labels: data, task

#72 bugs fixed
  milestone/milestone_3/total_analysis.ipynb
  milestone/milestone_3/updated_dataset.csv
Labels: bug, data

#70 add-documentation-milestone-4
  README.md
Labels: documentation

#73 Update_README_4_milestone
  README.md
Labels: bug, documentation

#68 Created retrospective 4
  retrospective/retrospective_4.md
Labels: documentation, task

#78 change README's and analysis files
  README.md
  milestone/milestone_3/README.md
  milestone/milestone_3/analysis_waste/README.md
  milestone/milestone_3/analysis_waste/analysis_food_service_waste.ipynb
  milestone/milestone_3/analysis_waste/analysis_household_waste.ipynb
  milestone/milestone_3/analysis_waste/analysis_retail_food_waste.ipynb
  milestone/milestone_3/research_questions.md
Labels: documentation, task

#79 Changes to main README
  README.md
  milestone/milestone_1/README.md
  milestone/milestone_2/README.md
  milestone/milestone_3/README.md
  milestone/milestone_4/README.md
Labels: bug, documentation
